name: Build

on: [push, pull_request]

jobs:
  build:
    name: CMake build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Install required packages
      run: |
        sudo apt-get update
        sudo apt-get install build-essential cmake libcjson-dev gettext
    - name: Build application
      run: |
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release .
        make -j3
